import React, { useEffect, useState } from "react";
import { ethers } from "ethers";
import { DEFAULT_NETWORK_ID, getNetworkById } from "../lib/networks";
import { withRpcFallback } from "../lib/inri";

type Tab = "dashboard"|"send"|"receive"|"tokens"|"nfts"|"activity"|"swap"|"bridge"|"settings";
export default function DashboardScreen({ setTab, theme, lang, address, activeNetworkId = DEFAULT_NETWORK_ID }: { setTab: (tab: Tab) => void; theme: "dark"|"light"; lang: string; address: string; activeNetworkId?: string; }) {
  const isLight = theme === "light"; const t = getText(lang); const network = getNetworkById(activeNetworkId);
  const [balance, setBalance] = useState("0"); const [blockNumber, setBlockNumber] = useState("--"); const [rpcUsed, setRpcUsed] = useState("-"); const [loading, setLoading] = useState(true);
  useEffect(() => { let mounted=true; async function load(){ if(!address){ if(mounted){setBalance("0");setLoading(false);} return;} setLoading(true); try { const result = await withRpcFallback(network, async (provider, rpcUrl) => { const [rawBalance, latestBlock] = await Promise.all([provider.getBalance(address), provider.getBlockNumber()]); return { balance: ethers.formatUnits(rawBalance, network.nativeCurrency.decimals), block: String(latestBlock), rpcUrl }; }); if(!mounted) return; setBalance(formatAmount(result.balance)); setBlockNumber(result.block); setRpcUsed(result.rpcUrl); } catch { if(!mounted) return; setBalance("0"); setBlockNumber("--"); setRpcUsed("RPC unavailable"); } finally { if(mounted) setLoading(false); } } load(); const timer = setInterval(load, 15000); return ()=>{ mounted=false; clearInterval(timer); }; }, [address, network]);
  return <div style={{display:"grid", gap:16}}><section style={heroCard(isLight)}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"center"}}><div><div style={{fontSize:13,fontWeight:700,color:isLight?"#5d6b85":"#9eabc4",marginBottom:8}}>{t.totalBalance}</div><div style={{fontSize:40,fontWeight:900,lineHeight:1,letterSpacing:"-0.04em",marginBottom:10}}>{loading?"...":balance} {network.nativeCurrency.symbol}</div><div style={{fontSize:13,color:isLight?"#5d6b85":"#9eabc4",wordBreak:"break-all"}}>{address || t.noAddress}</div></div><img src={network.icon} alt={network.name} style={{width:82,height:82,objectFit:"contain"}}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:10,marginTop:16}}><button onClick={()=>setTab("send")} style={primaryAction()}>{t.send}</button><button onClick={()=>setTab("receive")} style={secondaryAction(isLight)}>{t.receive}</button><button onClick={()=>setTab("tokens")} style={secondaryAction(isLight)}>{t.tokens}</button></div></section><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(180px, 1fr))",gap:12}}><InfoCard isLight={isLight} title={t.network} value={network.name} sub={`Chain ID: ${network.chainId}`} /><InfoCard isLight={isLight} title={t.latestBlock} value={blockNumber} sub={t.liveStatus} /><InfoCard isLight={isLight} title={t.rpcStatus} value={rpcUsed.includes("rpc-chain")?"Fallback RPC":"Main RPC"} sub={rpcUsed} /></section><section style={panel(isLight)}><div style={{fontSize:14,fontWeight:900,marginBottom:14,color:isLight?"#0f172a":"#fff"}}>{t.quickAccess}</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit, minmax(150px, 1fr))",gap:12}}><QuickButton isLight={isLight} label={t.activity} onClick={()=>setTab("activity")}/><QuickButton isLight={isLight} label={t.nfts} onClick={()=>setTab("nfts")}/><QuickButton isLight={isLight} label={t.swap} onClick={()=>setTab("swap")}/><QuickButton isLight={isLight} label={t.bridge} onClick={()=>setTab("bridge")}/><QuickButton isLight={isLight} label={t.settings} onClick={()=>setTab("settings")}/></div></section></div>;
}
function InfoCard({isLight,title,value,sub}:any){return <div style={{borderRadius:22,padding:16,border:`1px solid ${isLight?"#dbe2f0":"#252b39"}`,background:isLight?"rgba(255,255,255,.92)":"rgba(18,22,33,.92)"}}><div style={{fontSize:12,fontWeight:700,color:isLight?"#64748b":"#94a3b8",marginBottom:10}}>{title}</div><div style={{fontSize:20,fontWeight:900,color:isLight?"#0f172a":"#fff",marginBottom:8,wordBreak:"break-word"}}>{value}</div><div style={{fontSize:12,color:isLight?"#64748b":"#94a3b8",wordBreak:"break-word"}}>{sub}</div></div>}
function QuickButton({isLight,label,onClick}:any){return <button onClick={onClick} style={{padding:"16px 14px",borderRadius:18,border:`1px solid ${isLight?"#dbe2f0":"#252b39"}`,background:isLight?"#fff":"#131a29",color:isLight?"#0f172a":"#fff",cursor:"pointer",fontWeight:800,fontSize:14}}>{label}</button>}
function heroCard(isLight:boolean):React.CSSProperties{return{borderRadius:28,padding:20,border:`1px solid ${isLight?"#dbe2f0":"#252b39"}`,background:isLight?"linear-gradient(180deg, rgba(255,255,255,.96) 0%, rgba(245,248,253,.98) 100%)":"linear-gradient(180deg, rgba(15,22,36,.96) 0%, rgba(10,14,24,.98) 100%)"}}
function panel(isLight:boolean):React.CSSProperties{return{borderRadius:24,padding:18,border:`1px solid ${isLight?"#dbe2f0":"#252b39"}`,background:isLight?"rgba(255,255,255,.94)":"rgba(18,22,33,.94)"}}
function primaryAction():React.CSSProperties{return{padding:"14px 14px",borderRadius:16,border:"none",background:"#3f7cff",color:"#fff",fontWeight:900,cursor:"pointer",fontSize:14}}
function secondaryAction(isLight:boolean):React.CSSProperties{return{padding:"14px 14px",borderRadius:16,border:`1px solid ${isLight?"#dbe2f0":"#2a3348"}`,background:isLight?"#fff":"#141c2d",color:isLight?"#0f172a":"#fff",fontWeight:900,cursor:"pointer",fontSize:14}}
function formatAmount(value:string){const num=Number(value);if(!Number.isFinite(num)) return"0"; if(num===0)return"0"; if(num<0.0001)return num.toFixed(8); if(num<1)return num.toFixed(4); if(num<1000)return num.toFixed(3); return num.toLocaleString(undefined,{maximumFractionDigits:2});}
function getText(lang:string){const map:Record<string,any>={en:{totalBalance:"Total balance",noAddress:"No address loaded",send:"Send",receive:"Receive",tokens:"Tokens",network:"Network",latestBlock:"Latest block",liveStatus:"Live network status",rpcStatus:"RPC status",quickAccess:"Quick access",activity:"Activity",nfts:"NFTs",swap:"Swap",bridge:"Bridge",settings:"Settings"},pt:{totalBalance:"Saldo total",noAddress:"Nenhum endereço carregado",send:"Enviar",receive:"Receber",tokens:"Tokens",network:"Rede",latestBlock:"Último bloco",liveStatus:"Status da rede em tempo real",rpcStatus:"Status do RPC",quickAccess:"Acesso rápido",activity:"Atividade",nfts:"NFTs",swap:"Swap",bridge:"Bridge",settings:"Configurações"}};return map[lang]||map.en}
