import React, { useMemo } from "react";
import QRCode from "react-qr-code";
import { getNetworkById } from "../lib/networks";
import { getReceiveUri } from "../lib/inri";

export default function ReceiveScreen({ theme="dark", lang="en", address, activeNetworkId="inri" }:{theme?:"dark"|"light";lang?:string;address:string;activeNetworkId?:string;}) {
  const isLight = theme === "light"; const t = getText(lang); const network = getNetworkById(activeNetworkId); const qrValue = useMemo(() => getReceiveUri(activeNetworkId, address || "0x"), [activeNetworkId, address]);
  async function copyAddress(){ try{ await navigator.clipboard.writeText(address); alert(t.copied); }catch{ alert(t.copyFail);} }
  return <div style={{border:`1px solid ${isLight?"#dbe2f0":"#252b39"}`,borderRadius:20,background:isLight?"#ffffff":"#121621",padding:16}}><h2 style={{marginTop:0,color:isLight?"#10131a":"#ffffff"}}>{t.receive}</h2><div style={{color:isLight?"#5b6578":"#97a0b3",marginBottom:16}}>{network.name} • {network.chainId}</div><div style={{display:"grid",placeItems:"center",margin:"24px 0"}}><div style={{background:"#fff",padding:16,borderRadius:20}}><QRCode value={qrValue} size={190} /></div></div><div style={{padding:14,borderRadius:14,border:`1px solid ${isLight?"#dbe2f0":"#252b39"}`,background:isLight?"#f8fafc":"#0f1522",color:isLight?"#334155":"#cdd6ea",wordBreak:"break-all",fontSize:13}}>{address}</div><button onClick={copyAddress} style={{width:"100%",marginTop:14,padding:"14px 16px",borderRadius:14,border:"none",background:"#3f7cff",color:"#fff",cursor:"pointer",fontWeight:800,fontSize:16}}>{t.copyAddress}</button></div>;
}
function getText(lang:string){const map:any={en:{receive:"Receive",copyAddress:"Copy Address",copied:"Address copied.",copyFail:"Could not copy address."},pt:{receive:"Receber",copyAddress:"Copiar Endereço",copied:"Endereço copiado.",copyFail:"Não foi possível copiar o endereço."},es:{receive:"Recibir",copyAddress:"Copiar Dirección",copied:"Dirección copiada.",copyFail:"No se pudo copiar la dirección."},fr:{receive:"Recevoir",copyAddress:"Copier l’adresse",copied:"Adresse copiée.",copyFail:"Impossible de copier l’adresse."},de:{receive:"Empfangen",copyAddress:"Adresse kopieren",copied:"Adresse kopiert.",copyFail:"Adresse konnte nicht kopiert werden."},it:{receive:"Ricevi",copyAddress:"Copia indirizzo",copied:"Indirizzo copiato.",copyFail:"Impossibile copiare l’indirizzo."},ru:{receive:"Получить",copyAddress:"Скопировать адрес",copied:"Адрес скопирован.",copyFail:"Не удалось скопировать адрес."},zh:{receive:"接收",copyAddress:"复制地址",copied:"地址已复制。",copyFail:"无法复制地址。"},ja:{receive:"受取",copyAddress:"アドレスをコピー",copied:"アドレスをコピーしました。",copyFail:"アドレスをコピーできませんでした。"},ko:{receive:"수신",copyAddress:"주소 복사",copied:"주소가 복사되었습니다.",copyFail:"주소를 복사할 수 없습니다."},tr:{receive:"Al",copyAddress:"Adresi Kopyala",copied:"Adres kopyalandı.",copyFail:"Adres kopyalanamadı."}}; return map[lang]||map.en;}
